# Setup
version_name: panomtdu_dinov3Lp16_dpt_v7_cm_BFE_408k_combined
out_dir: "/mnt/localssd/PanoMTL/"

# Database
train_db_name: PanoMTDU
val_db_name: PanoMTDU
train_mode: train_gt
trBatch: 4
valBatch: 4
nworkers: 8
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: True
val_interval: 1000
epochs: 999999
max_iter: 180000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000005
scheduler: poly

# Model
model: TransformerBFE-DINO-DPT
backbone: dinov3L
head: dpt_head
embed_dim: 512
mtt_resolution_downsample_rate: 2
PRED_OUT_NUM_CONSTANT: 64

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_normals: True

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 1.0

grad_clip_param: {'max_norm': 10, 'norm_type': 2}
